FileVersion = 1
Dependencies = {corlib = "*", gtk-beef = "*"}

[Project]
Name = "libadwaita-beef"
TargetType = "BeefLib"
StartupObject = "libadwaita_beef.Program"

[Configs.Debug.Linux64]
BuildKind = "StaticLib"
OtherLinkFlags = "$(LinkFlags) -ladwaita-1"
